apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - start-dev
            - --import-realm
            - --metrics-enabled=true
            - --health-enabled=true
            - --features=token-exchange
            - --proxy-headers=xforwarded
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.admin.username }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: {{ .Values.admin.password }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master/.well-known/openid-configuration
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: realm
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: realm
          configMap:
            name: {{ .Release.Name }}-realm
