apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 9030
      targetPort: 9030
    - name: http
      port: 8030
      targetPort: 8030
    - name: be-http
      port: 8040
      targetPort: 8040
  selector:
    app: starrocks
